name: Continuous testing

# This workflow will run pytest on the latest commit of the master
# branch, but only after installing the package with pip.
# Indeed, it will not run the tests directly on the cloned code.
# It will only test it on the latest Ubuntu and on the latest python.

# It is set to be run automatically on each push to the master branch.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install the forest_puller package from repo
      run: pip install ./

    - name: Change directory after installation
      run: cd ../..

    - name: Install pytest
      run: pip install pytest

    - name: Test with pytest
      run: pytest --pyargs forest_puller