name: Continuous testing

# This workflow will run pytest on the latest commit of the master branch.
# It will only test it on the latest Ubuntu and on the latest python.

on: workflow_dispatch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Install the forest_puller package
      run: |
        pip install ./
    - name: Test with pytest
      run: |
        pytest