name: Test GitHub Workflow

# This workflow is used in the development environment to understand
# and test the github "Actions" technology.

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install the forest_puller package
      run: |
        pip install ./

    - name: Change directory after installation
      run: |
        cd ../..

    - name: Run a snippet
      run: |
        python -V