name: Test PyPI release

# This workflow will install the latest PyPI release of the package (not the
# master branch of the repository) and will run the README examples along pytest
# on various platforms. This includes Ubuntu and macOS, as well as four
# different python versions.

on: workflow_dispatch

env:
  readme_1: |
    from forest_puller.ipcc.country import countries
    austria = countries['AT']
    at_2017 = austria.years[2017].indexed
    print(at_2017.loc['remaining_forest', 'Coniferous']['net_co2'])
    print(at_2017.columns)
    print(at_2017.index)
    print(list(c.iso2_code for c in countries.values()))
    print(list(y for y in austria.years))

  readme_2: |
    from forest_puller.viz.converted_to_tons import converted_tons_data
    print(converted_tons_data.df)

  readme_3: |
    from forest_puller.ipcc.country import countries
    category, key = ['total_forest', 'biomass_net_change']
    biomass_net_change = {
        k: c.last_year.indexed.loc[category, ''][key]
        for k,c in countries.items()
    }
    import pprint
    pprint.pprint(biomass_net_change)

  readme_4: |
    from forest_puller.soef.country import countries
    country = countries['AT']
    print(country.forest_area.indexed)
    print(country.age_dist.indexed)
    print(country.fellings.indexed)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        python-version: ['3.6', '3.7', '3.8', '3.9']
        python-version: ['3.9']

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install the forest_puller package from PyPI
      run: |
        python -m pip install forest_puller

    - name: Run README 1
      run: |
        echo "${{ env.readme_1 }}" > readme_1.py
        python readme_1.py

    - name: Run README 2
      run: |
        echo "${{ env.readme_2 }}" > readme_2.py
        python readme_2.py

    - name: Run README 3
      run: |
        echo "${{ env.readme_3 }}" > readme_3.py
        python readme_3.py

    - name: Install pytest
      run: |
        python -m pip install pytest

    - name: Run the pytest suite
      run: |
        echo "Replace this"
