name: Test GitHub Workflow

# This workflow is used in the development environment to understand
# and test the github "Actions" technology.

on: workflow_dispatch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]


long_string: >-
  import forest_puller;
  print(forest_puller);
  x = 1;
  y = 3;
  print(x+y);

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install the forest_puller package
      run: |
        pip install ./

    - name: Change directory after installation
      run: |
        cd ../..

    - name: Save a snippet
      run: |
        echo ${{ long_string }} > nice_file.txt

    - name: Show a snippet
      run: |
        cat nice_file.txt